
export const profession = [
  'Accountant',
  'Actor /Actress',
  'Architect',
  'Astronomer',
  'Author',
  'Baker',
  'Builder /Bricklayer',
  'Driver',
  'Butcher',
  'Carpenter',
  'Chef/Cook',
  'Cleaner',
  'Dentist',
  'Designer',
  'Doctor',
  'Dustman/Refuse collector',
  'Electrician',
  'Engineer',
  'Factory worker',
  'Farmer',
  'Fireman/Fire fighter ',
  'Fisherman',
  'Florist',
  'Gardener',
  'Hairdresser',
  'Journalist',
  'Judge',
  'Lawyer',
  'Lecturer',
  'Librarian',
  'Lifeguard',
  'Mechanic',
  'Model',
  'Newsreader',
  'Nurse',
  'Optician',
  'Painter',
  'Pharmacist',
  'Photographer',
  'Pilot',
  'Plumber',
  'Politician',
  'Policeman /Policewoman',
  'Postman',
  'Real estate agent',
  'Receptionist',
  'Scientist',
  'Secretary',
  'Shop assistant /Seller',
  'Soldier',
  'Tailor',
  'Taxi driver',
  'Teacher',
  'Translator',
  'Travel agent',
  'Veterinary doctor',
  'Waiter/Waitress'
];
